tap 'caskroom/fonts'
tap 'caskroom/versions'

cask '1password'
cask 'alfred2'
cask 'bartender'
cask 'dash2'
cask 'docker'
cask 'google-chrome'
cask 'intellij-idea'
cask 'pycharm'
cask 'iterm2'
cask 'java'
cask 'slack'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'filezilla'
cask 'firefox'
cask 'grammarly'
cask 'postico'
cask 'postgres'
cask 'telegram'
cask 'viber'
cask 'spectacle'
cask 'teamviewer'
cask 'vlc'
cask 'font-hack-nerd-font'

# mas 'Xcode', id: 497799835

brew 'ansible'
brew 'aws-shell'
brew 'awscli'
brew 'awslogs'
brew 'bat'
brew 'cmake'
brew 'coreutils'
brew 'flake8'
brew 'ncdu'
brew 'openssl'
brew 'python'
brew 'python2'
brew 's3fs'
brew 'sbt'
brew 'tldr'
brew 'tmux'
brew 'wget'
brew 'zsh'
brew 'htop'
brew 'postgresql'
brew 'vim'

